import React from 'react';
import AppBar from "@material-ui/core/AppBar";
import { makeStyles } from "@material-ui/core/styles";

import Toolbar from "@material-ui/core/Toolbar";
import Avatar from "@material-ui/core/Avatar";
import {
  Tab,
  Tabs,
  Link
} from "@material-ui/core";
import cblogo from "../logo_icon.png";

const useStyles = makeStyles((theme) => ({
  grow: {
    flexGrow: 1,
  },
  appbar: {
    background: "#020642",
    boxShadow: "none",
    color: "white",
  },

}));
const AboutUs = () => {
  const classes = useStyles();
  return (
    <>
      <AppBar position="static" className={classes.appbar}>
        <Toolbar>
          <a href='/' style={{ textDecoration: "none", color: "white" }}>
            <h3 className={classes.title} noWrap style={{ letterSpacing: '2.0px' }}>
              CropCheck
            </h3>
          </a>
          <div className={classes.grow} />
          <Tabs className={classes.nav} value={false} aria-label="navigation menu" >
            <Tab label="Home" component={Link} href="/" />
            <Tab label="About" component={Link} href="/about" />
            <Tab label="Team" component={Link} href="/team" />
          </Tabs>
          <Avatar src={cblogo}></Avatar>
        </Toolbar>
      </AppBar>

      <div className="about-us-container" style={{ padding: "30px 20px" }}>
        <h1>About Us</h1>
        <p>
          Crop diseases are a major threat to food security, but their rapid identification
          remains difficult in many parts of the world due to the lack of the necessary
          infrastructure. <br />The combination of increasing global smartphone penetration and
          recent advances in computer vision made possible by deep learning has paved
          the way for smartphone-assisted disease diagnosis. Using a public dataset of
          2152 images of diseased and healthy plant leaves collected under controlled
          conditions, we train a deep convolutional neural network to identify 1 crop
          species and 2 diseases (or absence thereof). <br />The trained model achieves an
          accuracy of more than 91% on a held-out test set, demonstrating the feasibility of
          this approach. Overall, the approach of training deep learning models on
          increasingly large and publicly available image datasets presents a clear path
          toward smartphone-assisted crop disease diagnosis on a massive global scale.
        </p>
        <p>
          Modern technologies have given human society the ability to produce enough
          food to meet the demand of more than 7 billion people. However, food
          security remains threatened by a number of factors including climate change
          (Tai et al., 2014), the decline in pollinators (Report of the Plenary of the
          Intergovernmental Science-PolicyPlatform on Biodiversity Ecosystem and
          Services on the work of its fourth session, 2016), plant diseases (Strange and
          Scott, 2005), and others. <br />Plant diseases are not only a threat to food security
          at the global scale, but can also have disastrous consequences for smallholder
          farmers whose livelihoods depend on healthy crops. In the developing world,
          more than 80 percent of the agricultural production is generated by
          smallholder farmers (UNEP, 2013), and reports of yield loss of more than
          50% due to pests and diseases are common (Harvey et al., 2014). Furthermore,
          the largest fraction of hungry people (50%) live in smallholder farming
          households, making smallholder farmers a group that’s particularly
          vulnerable to pathogen-derived disruptions in food supply.
          <br />Various efforts have been developed to prevent crop loss due to diseases.
          Historical approaches of widespread application of pesticides have in the past
          decade increasingly been supplemented by integrated pest management (IPM)
          approaches. Independent of the approach, identifying a disease correctly when
          it first appears is a crucial step for efficient disease management.

        </p>

      </div>
    </>
  );
};

export default AboutUs;
